const fs = require('fs');
const path = require('path');

const inputDir = 'C:/MY FOLDER/Work/whatsease/src/app/comparision';
const outputFile = 'C:/MY FOLDER/Work/whatsease-landing/app/comparison/data.ts';

/**
 * Extracts the object literal assigned to `const <name> = { ... };`
 * from a source file, using brace counting that is aware of
 * single/double-quoted strings and backtick template literals.
 * Returns the raw object text (including surrounding braces) or null.
 */
function extractObject(content, name) {
  const marker = `const ${name} = {`;
  const idx = content.indexOf(marker);
  if (idx === -1) return null;

  let depth = 0;
  let inString = false;
  let inTemplate = false;
  let quote = '';

  for (let i = idx + marker.length - 1; i < content.length; i++) {
    const ch = content[i];

    if (inString) {
      if (ch === '\\') {
        i++; // skip escaped char
        continue;
      }
      if (ch === quote) inString = false;
      continue;
    }

    if (inTemplate) {
      if (ch === '\\') {
        i++;
        continue;
      }
      if (ch === '`') inTemplate = false;
      continue;
    }

    if (ch === '"' || ch === "'") {
      inString = true;
      quote = ch;
      continue;
    }
    if (ch === '`') {
      inTemplate = true;
      continue;
    }
    if (ch === '{') depth++;
    if (ch === '}') {
      depth--;
      if (depth === 0) {
        return content.slice(idx + marker.length - 1, i + 1);
      }
    }
  }
  return null;
}

const folders = fs
  .readdirSync(inputDir)
  .filter((f) => f.startsWith('whatsease-vs-'));

let finalData = `// Generated by extract.js from whatsease/src/app/comparision/*/page.tsx\n`;
finalData += `// Each entry: { data, heroContent } copied verbatim from the original source.\n`;
finalData += `export const comparisonsData: Record<string, any> = {\n`;

let count = 0;
for (const folder of folders) {
  const competitorId = folder.replace('whatsease-vs-', '').toLowerCase();
  const filePath = path.join(inputDir, folder, 'page.tsx');
  if (!fs.existsSync(filePath)) continue;

  const content = fs.readFileSync(filePath, 'utf8');
  const data = extractObject(content, 'data');
  const hero = extractObject(content, 'heroContent');

  if (data && hero) {
    finalData += `  "${competitorId}": { data: ${data}, heroContent: ${hero} },\n`;
    count++;
  } else {
    console.warn(`SKIPPED: ${folder} (data=${!!data}, heroContent=${!!hero})`);
  }
}

finalData += `};\n`;

fs.writeFileSync(outputFile, finalData, 'utf8');
console.log(`Extraction complete! ${count}/${folders.length} competitors extracted -> ${outputFile}`);
