// Generated by extract.js from whatsease/src/app/comparision/*/page.tsx
// Each entry: { data, heroContent } copied verbatim from the original source.
export const comparisonsData: Record<string, any> = {
  "bitespeed": { data: {
  title: 'Reasons to Choose',
  companyName: 'Whatsease',
  competitor: 'Bitespeed',
  features: [
    {
      title: 'WhatsApp-First Growth Engine vs. Ecommerce-Specific Platform',
      description:
        'Bitespeed is primarily an eCommerce platform that focuses on driving sales through SMS and WhatsApp marketing. WhatsEase.in is a <b> WhatsApp-first growth engine </b> that not only supports eCommerce sales but also powers <b>  event management, product launches, </b> and customer engagement through automated WhatsApp journeys — driving results across a variety of use cases. ',
      image: '/svg/comp/completeevent.svg',
      imageAlt: 'Complete event lifecycle',
      imageFirst: false,
    },
    {
      title: 'End-to-End Automation Across D2C & Events',
      description:
        "WhatsEase.in integrates <b> D2C sales funnels </b> with <b> event workflows,</b> offering features like WhatsApp-based registrations, ticketing, and QR check-ins. Bitespeed, while effective for product-based communication, doesn't offer comprehensive event management tools, limiting its use for brands running both online stores and offline experiences. ",
      image: '/svg/comp/realtime.svg',
      imageAlt: 'Real-time support',
      imageFirst: true,
    },
    {
      title: 'Smart Automation for Better ROI',
      description: `WhatsEase.in offers <b>personalized automation</b>, smart segmentation, and retargeting — leading to <b>8–10x ROAS </b> and up <b> to 80% reduced CAC. </b> Bitespeed focuses on SMS/WhatsApp marketing but lacks the depth of automation features that WhatsEase offers for driving <b> long-term customer engagement,</b> conversion, and event success. `,
      image: '/svg/comp/smartbulk.svg',
      imageAlt: 'Smart bulk messaging',
      imageFirst: false,
    },
  ],
}, heroContent: {
  headingHtml: `<h1>WhatsEase vs Bitespeed:</h1> <h1 class='mt-3'>A Deep Dive into <i class='text-black'>  WhatsApp-First Automation </i> vs eCommerce-Focused Messaging </h1>`,
  description:
    'WhatsEase goes beyond eCommerce—offering smart WhatsApp automation for both D2C growth and event management, unlike Bitespeed’s limited marketing tools.',
  buttonText: 'Try Now',
  mainImage: '/images/3.png',
  cornerImage: '/svg/comp/blackcurv.svg',
} },
  "business-on-bot": { data: {
  title: 'Reasons to Choose',
  companyName: 'Whatsease',
  competitor: 'Business on bot',
  features: [
    {
      title: 'Growth-Focused Platform vs. Generic Automation',
      description:
        'BusinessOnBot primarily provides automated communication for customer support and engagement. WhatsEase.in, however, is <b>  designed to drive growth </b> — offering tools tailored for <b>  D2C brands </b> and <b> event organizers </b> such as WhatsApp-based ticketing, personalized campaigns, and sales funnels that go beyond simple messaging.  ',
      image: '/svg/comp/completeevent.svg',
      imageAlt: 'Complete event lifecycle',
      imageFirst: false,
    },
    {
      title: 'Seamless Commerce & Event Integration',
      description:
        'WhatsEase.in integrates commerce and event flows seamlessly into the WhatsApp experience — from product recommendations and cart recovery to event registrations and QR check-ins. BusinessOnBot focuses on basic automation and lacks this level of cross-functional utility, making WhatsEase more versatile for diverse business needs.  ',
      image: '/svg/comp/realtime.svg',
      imageAlt: 'Real-time support',
      imageFirst: true,
    },
    {
      title: 'Smart Automation, Higher Efficiency',
      description:
        'WhatsEase.in optimizes customer engagement with <b>  automated product drops, reminders, and retargeting,</b> helping brands scale more effectively and reduce acquisition costs. BusinessOnBot, while efficient, lacks the same level of <b>  sales-driven automation </b> and <b>  conversion-centric workflows </b> that directly contribute to business growth. ',
      image: '/svg/comp/smartbulk.svg',
      imageAlt: 'Smart bulk messaging',
      imageFirst: false,
    },
  ],
}, heroContent: {
  headingHtml: `<h1>WhatsEase vs BusinessOnBot:</h1> <h1 class='mt-3'><i class='text-black'> All-in-One Growth </i> Engine for D2C & Events vs. Basic WhatsApp Automation</h1>`,
  description:
    'Weekend Bazaar used WhatsEase for ticket booking and entry management via WhatsApp, enhancing event operations and customer experience.',
  buttonText: 'Try Now',
  mainImage: '/images/12.png',
  cornerImage: '/svg/comp/blackcurv.svg',
} },
  "contlo": { data: {
  title: 'Reasons to Choose',
  companyName: 'Whatsease',
  competitor: 'Contlo',
  features: [
    {
      title: 'WhatsApp-Native vs. Omnichannel Overload',
      description:
        'While Contlo focuses on email, SMS, and other channels, WhatsEase.in is <b> built natively for WhatsApp,</b> where engagement and conversion rates are naturally higher. This focus allows brands to cut through the noise and connect faster — leading to better campaign efficiency without the bloat of managing multiple platforms.  ',
      image: '/svg/comp/completeevent.svg',
      imageAlt: 'Complete event lifecycle',
      imageFirst: false,
    },
    {
      title: ' Streamlined Funnels That Actually Convert',
      description:
        'WhatsEase.in offers tightly integrated workflows — from lead capture and product drops to abandoned cart recovery and event reminders — all in one place. This helps D2C brands convert more with fewer steps, ultimately driving stronger returns and reducing the cost of acquiring and re-engaging customers.  ',
      image: '/svg/comp/realtime.svg',
      imageAlt: 'Real-time support',
      imageFirst: true,
    },
    {
      title: 'Commerce + Community in One Platform',
      description:
        'Contlo lacks support for offline or hybrid brand experiences. WhatsEase.in bridges the gap by offering  <b> ticketing, registration, and QR check-ins, </b> making it ideal for D2C brands that run product launches, pop-ups, or community events alongside online campaigns. One tool, both channels — no silos.  ',
      image: '/svg/comp/smartbulk.svg',
      imageAlt: 'Smart bulk messaging',
      imageFirst: false,
    },
  ],
}, heroContent: {
  headingHtml: `<h1>WhatsEase vs Contlo:</h1> <h1 class='mt-3'> <i class='text-black'>WhatsApp-First Efficiency </i> vs. Omnichannel Overload</h1>`,
  description:
    'Weekend Bazaar used WhatsEase for ticket booking and entry management via WhatsApp, enhancing event operations and customer experience.',
  buttonText: 'Try Now',
  mainImage: '/images/4.png',
  cornerImage: '/svg/comp/blackcurv.svg',
} },
  "gallabox": { data: {
  title: 'Reasons to Choose',
  companyName: 'Whatsease',
  competitor: 'Gallabox',
  features: [
    {
      title: ' Full-Funnel Growth vs. Limited Messaging Solutions',
      description:
        "Gallabox primarily focuses on automating WhatsApp communication for customer support, including order tracking and updates. WhatsEase.in goes beyond simple messaging — it's a <b> growth-driven platform </b> that supports <b> D2C brands </b> and <b> event organizers </b> with tools like WhatsApp ticketing, retargeting, and personalized sales funnels, all within a single platform.  ",
      image: '/svg/comp/completeevent.svg',
      imageAlt: 'Complete event lifecycle',
      imageFirst: false,
    },
    {
      title: 'Unified D2C & Event Experience',
      description:
        'WhatsEase.in integrates both <b>  eCommerce </b> and <b> event workflows, </b> enabling businesses to run product campaigns, event registrations, and QR-based check-ins — all through WhatsApp. Gallabox, on the other hand, doesn’t offer event-specific features and is more focused on customer communication, making it less versatile for brands that want to scale across multiple use cases.  ',
      image: '/svg/comp/realtime.svg',
      imageAlt: 'Real-time support',
      imageFirst: true,
    },
    {
      title: 'Smart Automation for Higher Efficiency',
      description:
        'WhatsEase.in’s automated workflows allow brands to boost their <b>  ROAS </b> and <b> lower CAC </b> by engaging customers at the right touchpoints — from cart recovery to event reminders. Gallabox, while helpful for communication, lacks the same level of <b>  sales-driven automation </b> and comprehensive tools for long-term customer engagement and retention.  ',
      image: '/svg/comp/smartbulk.svg',
      imageAlt: 'Smart bulk messaging',
      imageFirst: false,
    },
  ],
}, heroContent: {
  headingHtml: `<h1>WhatsEase vs Gallabox:</h1> <h1 class='mt-3'> <i class='text-black'>Full-Funnel Growth </i> vs. Limited Customer Messaging Solutions</h1>`,
  description:
    'Weekend Bazaar used WhatsEase for ticket booking and entry management via WhatsApp, enhancing event operations and customer experience.',
  buttonText: 'Try Now',
  mainImage: '/images/5.png',
  cornerImage: '/svg/comp/blackcurv.svg',
} },
  "interakt": { data: {
  title: 'Reasons to Choose',
  companyName: 'Whatsease',
  competitor: 'Interakt',
  features: [
    {
      title: 'Purpose-Built for D2C Growth',
      description:
        'WhatsEase.in is designed to help D2C brands drive conversions and customer engagement directly on WhatsApp. From abandoned cart recovery to product recommendations and order updates, it’s tailored for sales growth. Interakt supports basic commerce features, but lacks the flexibility and depth for high-conversion campaigns. ',
      image: '/svg/comp/completeevent.svg',
      imageAlt: 'Complete event lifecycle',
      imageFirst: false,
    },
    {
      title: 'All-in-One Engagement Platform',
      description:
        "Whether you're hosting an event or running a D2C campaign, WhatsEase.in handles registrations, payments, broadcasts, and customer journeys — all in one place. Interakt requires workarounds or third-party tools to cover multiple use cases, often leading to fragmented experiences. ",
      image: '/svg/comp/realtime.svg',
      imageAlt: 'Real-time support',
      imageFirst: true,
    },
    {
      title: 'Smarter Automation with Custom Flows',
      description:
        'With WhatsEase.in, you can set up intelligent flows for product drops, restock alerts, ticketing, or post-purchase engagement — without writing code. It adapts to both one-time and ongoing campaigns. Interakt’s automation is functional but more rigid, limiting personalized experiences. ',
      image: '/svg/comp/smartbulk.svg',
      imageAlt: 'Smart bulk messaging',
      imageFirst: false,
    },
  ],
}, heroContent: {
  headingHtml: `<h1> WhatsEase vs Interakt:</h1> <h1 class='mt-3'> <i class='text-black'>Purpose-Built D2C Growth</i> vs. Basic Automation Solutions</h1>`,
  description:
    'Weekend Bazaar used WhatsEase for ticket booking and entry management via WhatsApp, enhancing event operations and customer experience.',
  buttonText: 'Try Now',
  mainImage: '/images/6.png',
  cornerImage: '/svg/comp/blackcurv.svg',
} },
  "kwikchat": { data: {
  title: 'Reasons to Choose',
  companyName: 'Whatsease',
  competitor: 'Kwikchat',
  features: [
    {
      title: 'WhatsApp-First Growth Engine vs. Chat-Only Support',
      description:
        'KwikChat is primarily a live chat tool that integrates with WhatsApp for customer support. WhatsEase.in is <b>  built to drive growth,</b> offering a <b>  full-funnel WhatsApp experience </b> — from lead capture, product recommendations, and abandoned cart recovery to event ticketing and post-sale engagement, all within WhatsApp.  ',
      image: '/svg/comp/completeevent.svg',
      imageAlt: 'Complete event lifecycle',
      imageFirst: false,
    },
    {
      title: 'Seamless Integration for Events & D2C',
      description:
        'WhatsEase.in combines <b> eCommerce and event workflows </b> in one platform — allowing D2C brands to automate sales funnels, send reminders, and manage event registrations without needing additional tools. KwikChat’s focus is more limited to customer service and doesn’t offer event management or sales-specific automation.  ',
      image: '/svg/comp/realtime.svg',
      imageAlt: 'Real-time support',
      imageFirst: true,
    },
    {
      title: ' Automated Campaigns with Higher Efficiency ',
      description:
        'WhatsEase.in helps brands achieve <b>8-10x ROAS and 80% lower CAC </b> through smart segmentation and personalized automation across both <b> D2C and event </b> use cases. KwikChat, while strong on real-time chat, lacks the same depth of <b> automation and conversion-driven tools </b> for sustained business growth.  ',
      image: '/svg/comp/smartbulk.svg',
      imageAlt: 'Smart bulk messaging',
      imageFirst: false,
    },
  ],
}, heroContent: {
  headingHtml: `<h1>WhatsEase vs KwikChat:</h1> <h1 class='mt-3'> <i class='text-black'>Full-Funnel Growth</i> vs. Chat-Only Support</h1>`,
  description:
    'Weekend Bazaar used WhatsEase for ticket booking and entry management via WhatsApp, enhancing event operations and customer experience.',
  buttonText: 'Try Now',
  mainImage: '/images/7.png',
  cornerImage: '/svg/comp/blackcurv.svg',
} },
  "limechat": { data: {
  title: 'Reasons to Choose',
  companyName: 'Whatsease',
  competitor: 'Limechat',
  features: [
    {
      title: '8–10x ROAS vs. Chat-Only Conversions',
      description:
        'WhatsEase.in delivers <b> 8–10x return on ad spend (ROAS) </b> by combining WhatsApp automation with payment collection, upselling flows, and post-sale engagement — all in one journey. LimeChat focuses heavily on AI-powered chat, which is great for support, but lacks the end-to-end funnel optimization needed for such high ROAS performance.  ',
      image: '/svg/comp/completeevent.svg',
      imageAlt: 'Complete event lifecycle',
      imageFirst: false,
    },
    {
      title: '80% Lower CAC with Built-in Retargeting',
      description:
        'WhatsEase.in helps D2C brands <b> reduce customer acquisition cost (CAC) by up to 80% </b> using retargeting, automated product drops, and behavioral broadcasts directly on WhatsApp. LimeChat mostly captures users after they land on your store, while WhatsEase proactively engages them across the funnel — from lead gen to repeat purchase. . ',
      image: '/svg/comp/realtime.svg',
      imageAlt: 'Real-time support',
      imageFirst: true,
    },
    {
      title: ' Not Just Support, Full-Funnel Growth',
      description:
        'LimeChat shines as a conversational support tool, but it lacks features like ticketing, real-time reminders, campaign scheduling, or QR-based event check-ins. WhatsEase.in, by contrast, is built for <b> growth-first use cases, </b> supporting both D2C commerce and hybrid/IRL campaigns — making it a better fit for fast-scaling brands.  ',
      image: '/svg/comp/smartbulk.svg',
      imageAlt: 'Smart bulk messaging',
      imageFirst: false,
    },
  ],
}, heroContent: {
  headingHtml: `<h1>WhatsEase vs LimeChat:</h1> <h1 class='mt-3'><i class='text-black'>8-10x ROAS & Full-Funnel Growth </i>vs. Chat-Only Support<h1>`,
  description:
    'Weekend Bazaar used WhatsEase for ticket booking and entry management via WhatsApp, enhancing event operations and customer experience.',
  buttonText: 'Try Now',
  mainImage: '/images/8.png',
  cornerImage: '/svg/comp/blackcurv.svg',
} },
  "sinch": { data: {
  title: 'Reasons to Choose',
  companyName: 'Whatsease',
  competitor: 'Sinch',
  features: [
    {
      title: 'Tailored for D2C & Events vs. Infrastructure-Led Messaging',
      description:
        'Sinch is a global communications infrastructure platform — great for enterprises needing SMS, email, or voice at scale. WhatsEase.in is purpose-built for <b>  D2C brands and event organizers,</b>  offering pre-built tools like WhatsApp ticketing, product drops, and real-time customer journeys — all without developer dependency.   ',
      image: '/svg/comp/completeevent.svg',
      imageAlt: 'Complete event lifecycle',
      imageFirst: false,
    },
    {
      title: 'Out-of-the-Box Growth Tools',
      description:
        'WhatsEase.in offers ready-to-launch flows for abandoned carts, restock alerts, and campaign broadcasts — helping brands convert more and grow faster. While Sinch provides APIs and SDKs, it requires heavy lifting to create similar experiences, which can delay go-to-market speed and dilute performance gains.  ',
      image: '/svg/comp/realtime.svg',
      imageAlt: 'Real-time support',
      imageFirst: true,
    },
    {
      title: 'Simplified CX, Higher Engagement',
      description:
        'With WhatsEase.in, brands get a full-funnel WhatsApp experience — from first click to check-out to post-purchase care. This <b>  higher engagement naturally boosts ROAS and lowers acquisition costs, </b> especially when compared to generic messaging routes like SMS or email offered by Sinch.   ',
      image: '/svg/comp/smartbulk.svg',
      imageAlt: 'Smart bulk messaging',
      imageFirst: false,
    },
  ],
}, heroContent: {
  headingHtml: `<h1>WhatsEase vs Sinch:</h1> <h1 class='mt-3'> <i class='text-black'>Tailored D2C Growth </i> vs. Infrastructure-Led Messaging</h1>`,
  description:
    'Weekend Bazaar used WhatsEase for ticket booking and entry management via WhatsApp, enhancing event operations and customer experience.',
  buttonText: 'Try Now',
  mainImage: '/images/9.png',
  cornerImage: '/svg/comp/blackcurv.svg',
} },
  "superlemon": { data: {
  title: 'Reasons to Choose',
  companyName: 'Whatsease',
  competitor: 'superlemon',
  features: [
    {
      title: 'Beyond Just Shopify Plugins',
      description:
        'SuperLemon mainly functions as a WhatsApp plugin for Shopify, with features like order updates and basic automation. WhatsEase.in, on the other hand, is a full-fledged WhatsApp-first platform built for both <b> eCommerce and events,</b> offering custom journeys, payment flows, reminders, and ticketing — without being limited to just one platform.  ',
      image: '/svg/comp/completeevent.svg',
      imageAlt: 'Complete event lifecycle',
      imageFirst: false,
    },
    {
      title: 'Multi-Use Case Powerhouse',
      description:
        "WhatsEase.in caters to both <b> D2C brands </b> (with features like product drops, restock alerts, cart recovery) and <b>event hosts </b> (registration, QR ticketing, check-ins). SuperLemon is tightly tied to online stores and doesn't support events or offline campaigns, which limits growth opportunities beyond Shopify.  ",
      image: '/svg/comp/realtime.svg',
      imageAlt: 'Real-time support',
      imageFirst: true,
    },
    {
      title: 'Automation That Converts, Not Just Notifies',
      description:
        'While SuperLemon offers transactional alerts, WhatsEase.in is built to <b>drive action </b> — whether it’s making a purchase, signing up for an event, or showing up on time. With smart segmentation, personalized broadcasts, and flexible automation, WhatsEase is geared toward conversions, not just communication.  ',
      image: '/svg/comp/smartbulk.svg',
      imageAlt: 'Smart bulk messaging',
      imageFirst: false,
    },
  ],
}, heroContent: {
  headingHtml: `<h1>WhatsEase vs SuperLemon:</h1> <h1 class='mt-3'><i class='text-black'>Full-Featured Growth Platform</i> vs. Shopify-Only Plugin</h1>`,
  description:
    'Weekend Bazaar used WhatsEase for ticket booking and entry management via WhatsApp, enhancing event operations and customer experience.',
  buttonText: 'Try Now',
  mainImage: '/images/10.png',
  cornerImage: '/svg/comp/blackcurv.svg',
} },
  "wati": { data: {
  title: 'Reasons to Choose',
  companyName: 'Whatsease',
  competitor: 'Wati',
  features: [
    {
      title: 'Built for D2C and Events, Not Just Support',
      description:
        'WhatsEase.in goes beyond just customer support — it’s a revenue-focused platform for D2C brands and event organizers. You can drive product launches, run campaigns, automate sales funnels, or manage ticketed events. WATI is great for support teams, but lacks native tools for growth-focused use cases like ticketing or WhatsApp-driven conversions.  ',
      image: '/svg/comp/completeevent.svg',
      imageAlt: 'Complete event lifecycle',
      imageFirst: false,
    },
    {
      title: 'Custom Journeys without Code',
      description:
        "With WhatsEase.in, you can build automated, personalized flows for sales, registrations, order confirmations, reminders, and QR-based check-ins — all through a visual, no-code interface. WATI offers some automation, but customization is limited unless you're working with developers or external tools like Dialogflow.  ",
      image: '/svg/comp/realtime.svg',
      imageAlt: 'Real-time support',
      imageFirst: true,
    },
    {
      title: 'Event-Ready + Commerce-Smart',
      description:
        'WhatsEase is one of the few platforms that combines <b>event ticketing, D2C workflows,</b> and <b>WhatsApp automation</b> in one product. From sending QR codes to tracking guest check-ins or automating restock alerts — it’s all covered. WATI doesn’t natively support event management or end-to-end commerce journeys in the same way.  ',
      image: '/svg/comp/smartbulk.svg',
      imageAlt: 'Smart bulk messaging',
      imageFirst: false,
    },
  ],
}, heroContent: {
  headingHtml: `<h1>WhatsEase vs Wati:</h1> <h1 class='mt-3'><i class='text-black'>D2C & Event Growth Platform</i> vs. Support-Focused Automation</h1>`,
  description:
    'Weekend Bazaar used WhatsEase for ticket booking and entry management via WhatsApp, enhancing event operations and customer experience.',
  buttonText: 'Try Now',
  mainImage: '/images/2.png',
  cornerImage: '/svg/comp/blackcurv.svg',
} },
  "zoko": { data: {
  title: 'Reasons to Choose',
  companyName: 'Whatsease',
  competitor: 'Zoko',
  features: [
    {
      title: 'More Than a Sales Channel — A Full Funnel Engine',
      description:
        "Zoko is focused on using WhatsApp as a sales channel by linking carts, products, and transactions. WhatsEase.in goes much deeper — it enables <b> end-to-end funnels </b> with lead capture, behavioral automation, reminders, payments, ticketing, and QR check-ins. It's not just about selling, it’s about <b> lifecycle growth </b> across D2C and events.   ",
      image: '/svg/comp/completeevent.svg',
      imageAlt: 'Complete event lifecycle',
      imageFirst: false,
    },
    {
      title: '8–10x ROAS & 80% Lower CAC',
      description:
        'WhatsEase.in consistently delivers  <b> 8–10x ROAS </b> through smarter segmentation, abandoned cart nudges, and personalized campaigns. With integrated retargeting, brands have seen <b> up to 80% reduction in CAC. </b> Zoko supports broadcasts and flows, but often requires additional tools to match this level of performance and cost-efficiency.  ',
      image: '/svg/comp/realtime.svg',
      imageAlt: 'Real-time support',
      imageFirst: true,
    },
    {
      title: 'Events + Commerce in One Platform',
      description:
        'Unlike Zoko — which is focused on D2C stores only — WhatsEase.in uniquely blends <b> event workflows (ticketing, registration, check-ins) with D2C commerce flows.</b> This makes it ideal for brands running pop-ups, workshops, product launches, or experiential campaigns alongside online sales — no third-party tools needed.  ',
      image: '/svg/comp/smartbulk.svg',
      imageAlt: 'Smart bulk messaging',
      imageFirst: false,
    },
  ],
}, heroContent: {
  headingHtml: `<h1>WhatsEase vs Zoko:</h1> <h1 class='mt-3'><i class='text-black'> Full-Funnel Growth </i> vs. Sales-Only Focus</h1>`,
  description:
    'Weekend Bazaar used WhatsEase for ticket booking and entry management via WhatsApp, enhancing event operations and customer experience.',
  buttonText: 'Try Now',
  mainImage: '/images/11.png',
  cornerImage: '/svg/comp/blackcurv.svg',
} },
};
